services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    # tool: installer
    Youwe\Pimcore\WorkflowGui\Installer\WorkflowGuiInstaller:
        public: true
        arguments:
            $bundle: "@=service('kernel').getBundle('WorkflowGuiBundle')"

