services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    # tool: installer
    Youwe\Pimcore\WorkflowGui\MigrationInstaller:
        arguments:
            $bundle: "@=service('kernel').getBundle('WorkflowGuiBundle')"
            $configFileResolver: '@Youwe\Pimcore\WorkflowGui\Resolver\ConfigFileResolver'
