workflow_gui.admin.list:
    path: /admin/workflow/list
    defaults: { _controller: WorkflowGuiBundle:Workflow:list }

workflow_gui.admin.get:
    path: /admin/workflow/get
    defaults: { _controller: WorkflowGuiBundle:Workflow:get }

workflow_gui.admin.save:
    path: /admin/workflow/save
    methods: [POST]
    defaults: { _controller: WorkflowGuiBundle:Workflow:save }

workflow_gui.admin.delete:
    path: /admin/workflow/delete
    methods: [POST]
    defaults: { _controller: WorkflowGuiBundle:Workflow:delete }

workflow_gui.roles.search:
    path: /admin/workflow/roles/search
    defaults: { _controller: WorkflowGuiBundle:Workflow:searchRoles }

workflow_gui.admin.get-classes:
    path: /admin/workflow/get-classes
    defaults: { _controller: WorkflowGuiBundle:Workflow:getClasses }
